//made with ai
const products = [
  { id: 1, name: "Laptop Acer", price: 700, categories: ["Electronics", "Computers"], description: "Acer laptop with 8GB RAM and 256GB SSD" },
  { id: 2, name: "Smartphone Samsung", price: 500, categories: ["Electronics", "Mobile"], description: "Samsung Galaxy smartphone with 128GB storage" },
  { id: 3, name: "Headphones Sony", price: 150, categories: ["Electronics", "Audio"], description: "Sony noise-cancelling headphones" },
  { id: 4, name: "Smart TV LG", price: 800, categories: ["Electronics", "Home Appliances"], description: "55-inch 4K Smart TV by LG" },
  { id: 5, name: "Gaming Mouse Logitech", price: 60, categories: ["Electronics", "Accessories"], description: "Logitech gaming mouse with RGB lighting" },
  { id: 6, name: "Mechanical Keyboard", price: 100, categories: ["Electronics", "Accessories"], description: "Mechanical keyboard with Cherry MX switches" },
  { id: 7, name: "Wireless Earbuds", price: 120, categories: ["Electronics", "Audio"], description: "Wireless earbuds with noise cancellation" },
  { id: 8, name: "Smartwatch Apple", price: 400, categories: ["Electronics", "Wearables"], description: "Apple smartwatch with fitness tracking" },
  { id: 9, name: "Tablet Lenovo", price: 250, categories: ["Electronics", "Tablets"], description: "10-inch Lenovo tablet with 64GB storage" },
  { id: 10, name: "Digital Camera Canon", price: 900, categories: ["Electronics", "Cameras"], description: "Canon DSLR camera with 24MP sensor" },
  { id: 11, name: "Air Fryer", price: 80, categories: ["Home Appliances", "Kitchen"], description: "Compact air fryer for healthy cooking" },
  { id: 12, name: "Electric Kettle", price: 30, categories: ["Home Appliances", "Kitchen"], description: "Electric kettle with fast boiling" },
  { id: 13, name: "Espresso Machine", price: 250, categories: ["Home Appliances", "Kitchen"], description: "Espresso machine for coffee lovers" },
  { id: 14, name: "Blender", price: 60, categories: ["Home Appliances", "Kitchen"], description: "High-power blender for smoothies" },
  { id: 15, name: "Microwave Oven", price: 100, categories: ["Home Appliances", "Kitchen"], description: "Compact microwave oven" },
  { id: 16, name: "Vacuum Cleaner", price: 150, categories: ["Home Appliances", "Cleaning"], description: "Powerful vacuum cleaner with HEPA filter" },
  { id: 17, name: "Gaming Console", price: 500, categories: ["Electronics", "Gaming"], description: "Next-gen gaming console" },
  { id: 18, name: "Yoga Mat", price: 20, categories: ["Sports", "Fitness"], description: "Non-slip yoga mat" },
  { id: 19, name: "Dumbbell Set", price: 50, categories: ["Sports", "Fitness"], description: "Adjustable dumbbell set" },
  { id: 20, name: "Mountain Bike", price: 300, categories: ["Sports", "Outdoor"], description: "Mountain bike with 21 gears" },
  { id: 21, name: "Camping Tent", price: 100, categories: ["Outdoor", "Camping"], description: "Two-person camping tent" },
  { id: 22, name: "Backpack", price: 40, categories: ["Accessories", "Outdoor"], description: "Durable backpack for hiking" },
  { id: 23, name: "Electric Scooter", price: 350, categories: ["Transportation", "Outdoor"], description: "Electric scooter with 20km range" },
  { id: 24, name: "Office Chair", price: 120, categories: ["Furniture", "Office"], description: "Ergonomic office chair with lumbar support" },
  { id: 25, name: "Desk Lamp", price: 25, categories: ["Home Decor", "Lighting"], description: "LED desk lamp with adjustable brightness" },
  { id: 26, name: "Wireless Charger", price: 30, categories: ["Electronics", "Accessories"], description: "Fast wireless charger for smartphones" },
  { id: 27, name: "Smart Light Bulb", price: 20, categories: ["Home Automation", "Lighting"], description: "Color-changing smart bulb compatible with voice control" },
  { id: 28, name: "Portable Speaker JBL", price: 80, categories: ["Electronics", "Audio"], description: "Waterproof portable speaker with deep bass" },
  { id: 29, name: "Air Purifier", price: 120, categories: ["Home Appliances", "Health"], description: "HEPA air purifier for clean indoor air" },
  { id: 30, name: "Standing Desk", price: 300, categories: ["Furniture", "Office"], description: "Adjustable standing desk for ergonomic workspace" },
  { id: 31, name: "Portable Power Bank", price: 25, categories: ["Electronics", "Accessories"], description: "Compact power bank with 10000mAh capacity" },
  { id: 32, name: "Pressure Cooker", price: 70, categories: ["Home Appliances", "Kitchen"], description: "Electric pressure cooker for fast meal prep" },
  { id: 33, name: "Robot Vacuum", price: 250, categories: ["Home Appliances", "Cleaning"], description: "Automatic robot vacuum with smart mapping" },
  { id: 34, name: "Foam Roller", price: 15, categories: ["Sports", "Fitness"], description: "Foam roller for muscle recovery and massage" },
  { id: 35, name: "Electric Toothbrush", price: 40, categories: ["Personal Care", "Health"], description: "Rechargeable electric toothbrush with soft bristles" },
  { id: 36, name: "LED Monitor", price: 200, categories: ["Electronics", "Computers"], description: "24-inch LED monitor with full HD resolution" },
  { id: 37, name: "Smart Lock", price: 150, categories: ["Home Automation", "Security"], description: "Smart lock with app control and remote access" },
  { id: 38, name: "Dehumidifier", price: 180, categories: ["Home Appliances", "Health"], description: "Compact dehumidifier for small rooms" },
  { id: 39, name: "Electric Skateboard", price: 400, categories: ["Sports", "Outdoor"], description: "Electric skateboard with 15-mile range" },
  { id: 40, name: "Security Camera", price: 100, categories: ["Home Automation", "Security"], description: "Indoor security camera with night vision" },
  { id: 41, name: "Bluetooth Keyboard", price: 50, categories: ["Electronics", "Accessories"], description: "Wireless Bluetooth keyboard for tablets and phones" },
  { id: 42, name: "HD Projector", price: 350, categories: ["Electronics", "Home Theater"], description: "Portable HD projector for movies and presentations" },
  { id: 43, name: "Ceramic Heater", price: 60, categories: ["Home Appliances", "Heating"], description: "Energy-efficient ceramic heater for small spaces" },
  { id: 44, name: "Water Bottle", price: 10, categories: ["Accessories", "Outdoor"], description: "Stainless steel water bottle with 500ml capacity" },
  { id: 45, name: "Massage Gun", price: 120, categories: ["Health", "Fitness"], description: "Handheld massage gun for muscle relaxation" },
  { id: 46, name: "Smart Thermostat", price: 200, categories: ["Home Automation", "Heating"], description: "Wi-Fi-enabled smart thermostat" },
  { id: 47, name: "Camping Stove", price: 40, categories: ["Outdoor", "Camping"], description: "Portable gas camping stove for outdoor cooking" },
  { id: 48, name: "Waterproof Jacket", price: 60, categories: ["Clothing", "Outdoor"], description: "Lightweight waterproof jacket for hiking" },
  { id: 49, name: "3D Printer", price: 500, categories: ["Electronics", "Creativity"], description: "Desktop 3D printer with high precision" },
  { id: 50, name: "Noise Machine", price: 25, categories: ["Health", "Sleep"], description: "White noise machine for better sleep" },

];


module.exports = products